export { default as CartEmptyBold } from './CartEmptyBold'
export { default as CartFilledBold } from './CartFilledBold'
export { default as NotifyBold } from './NotifyBold'
export { default as ProfileBold } from './ProfileBold'
export { default as SearchBold } from './SearchBold'
export { default as SettingsBold } from './SettingsBold'
export { default as SupportBold } from './SupportBold'
export { default as UserAddBold } from './UserAddBold'
