version: 2.1

executors:
  builder:
    docker:
      - image: telus/build-essential

  browsers:
    docker:
      - image: circleci/node:8-browsers

dependencies:
  pre:
    - google-chrome --version
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub 54 | sudo apt-key add -
    - sudo sh -c ‘echo “deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ 27 stable main” >> /etc/apt/sources.list.d/google.list’
    - sudo apt-get update
    - sudo apt-get --only-upgrade install google-chrome-stable
    - google-chrome --version

commands:
  persist:
    steps:
      - persist_to_workspace:
          root: .
          paths: .

  attach:
    steps:
      - attach_workspace:
          at: .

  install:
    steps:
      - run:
          name: Install dependencies
          command: npm ci

jobs:
  build:
    executor: builder
    steps:
      - checkout
      - run:
          name: Bootstrap
          command: npm run bootstrap:ci
      - persist

  lint:
    executor: builder
    steps:
      - attach
      - run: npm run lint

  unit:
    executor: builder
    steps:
      - attach
      - run: npm run test

  e2e:
    executor: browsers
    steps:
      - attach
      - run:
          name: Prepare node-sass
          command: npm rebuild node-sass
      - run:
          name: Styleguidist Server
          command: npm run dev:e2e-direct
          background: true
      - run: npm run test:e2e-direct -- -a
      - run:
          name: TDS Bot Analysis
          when: on_success
          command: if [ "$CIRCLE_PULL_REQUEST" != "false" ]; then scripts/prePr.sh ; node ./scripts/circleci/github-pr.js ; fi

  release:
    executor: builder
    steps:
      - attach
      - run: npx semantic-release

workflows:
  version: 2
  run:
    jobs:
      - build

      - lint:
          requires: [build]

      - unit:
          requires: [build]

      - e2e:
          requires: [build]

      - release:
          context: npm-library
          requires: [build, lint, unit, e2e]
          filters:
            branches:
              only: master
