# The docker-compose.yml describes all the services in our application. While Docker Compose is best suited for
#  multi-container applications, we can use it to simplify our interaction with Docker.
#  https://docs.docker.com/compose/overview/

# `docker-compose build` --> Build the image. Do this first.
# `docker images` --> View the image you just built

version: '3'
services:
  ciboot:
    container_name: tds-core
    build: .
    ports:
      - 6060:6060
    volumes:
      - './:/tds-core/'
  e2e:
    container_name: tds-core-e2e
    build:
      context: .
      dockerfile: e2e/Dockerfile
    environment:
      - mode=-a
    entrypoint:
      - npm
      - run
      - test:e2e-direct
      - --
      - $mode
    network_mode: host
    ports:
      - 6060:6060
    depends_on:
      - ciboot
    volumes:
      - './e2e/.:/tds-core/e2e/'
      - './scripts/.:/tds-core/scripts/'
      - './config/.:/tds-core/config/'
      - './packages/.:/tds-core/packages/'
      - './shared/.:/tds-core/shared/'
      - './.git/.:/tds-core/.git/'
      - '${PWD}/lerna.json:/tds-core/lerna.json'
      - '${PWD}/babel.config.js:/tds-core/babel.config.js'
